### ISSUE TITLE
RuntimeError: HHSearch failed:

### ISSUE THREAD

**Issue by mestia** [uvarc/rivanna-docker#2]
Thank you for providing the singularity image, however when running the image the way you described it here:
https://github.com/deepmind/alphafold/issues/10#issuecomment-888556068
I get this error:

```I0804 10:53:22.216594 139881170892608 hhsearch.py:76] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmptf8vv9v7/query.a3m -o /tmp/tmptf8vv9v7/output.hhr -maxseq 1000000 -d /data/pdb70/pdb70"
I0804 10:53:22.427164 139881170892608 utils.py:36] Started HHsearch query
I0804 10:53:22.626598 139881170892608 utils.py:40] Finished HHsearch query in 0.199 seconds
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 303, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 277, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 127, in predict_structure
    feature_dict = data_pipeline.process(
  File "/app/alphafold/alphafold/data/pipeline.py", line 141, in process
    hhsearch_result = self.hhsearch_pdb70_runner.query(uniref90_msa_as_a3m)
  File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 85, in query
    raise RuntimeError(
RuntimeError: HHSearch failed:
stdout:


stderr:
```

Any hint about what could be wrong?
Thank you!

**Comment by rsdmse** [comment]
We're not seeing this error on our platform. Have you downloaded the entire database and bind-mounted the correct paths on your machine?

Our documentation for Rivanna (UVA's HPC cluster) users can be found [here](https://www.rc.virginia.edu/userinfo/rivanna/software/alphafold/). Unfortunately, it's beyond our capabilities to troubleshoot this for other institutions. Comparing with the comment you quoted, we don't have the environment variable regarding memory, but I doubt that's the issue here.

There is a [similar issue](https://github.com/deepmind/alphafold/issues/49) reported on DeepMind's repo. I suggest that you reach out to that person to see how the issue was resolved.

**Comment by mestia** [comment]
Thank you for your quick reaction, the database is bind mounted and I'll double check the path.

**Comment by SoniaAndrys** [comment]
Hi @mestia, I am dealing with the same issue right now, have you already come up with what is wrong? Any tips? Database is mounted and my paths are correct, yet I am still getting the "HHSearch failed:" error. 
I will appreciate any tip from you!

Best regards,
Sonia

**Comment by rsdmse** [comment]
I found this suggestion on the alphafold repo: https://github.com/deepmind/alphafold/issues/97#issuecomment-895019659

**Comment by SoniaAndrys** [comment]
Thank you, @rsdmse - will try :)

**Comment by seb45tian** [comment]
Hi, I ran into the same error. Issue for me was, that I **build** the image myself (the original deepmind one) on a skylake CPU and was trying to run it on an ivybridge node. After some diggin' I ran the /usr/bin/hhsearch command itself inside the container and got a segfault -  this makes sense as it is compiled within the build procedure of the image and the container might therefore be CPU architecture specific. I hope this helps.

**Comment by rsdmse** [comment]
Our local users have not reported this issue. Please follow up with DeepMind. Thanks everyone for the input.

**Comment by yunxiangz** [comment]
Hi @rsdmse , could you explain how you increase the mem and the number of GPU, please? (e.g., with parameters in the python script? or via system settings?)
If possible, could you also share the command that you used to solve this problem? 

PS: I am running locally without docker.

Thank you so much!

**Comment by cfgauss** [comment]
I can confirm that on our university HPC machines, increasing memory and cores to SLURM parameters
`--mem=62GB`
`-c 16`
got rid of this error for us.
